{"uuid": "1d797b55-c604-4737-bb19-60560db4834f", "children": ["2f26b680-51be-446c-89df-efe2bdafd08d"], "befores": [{"name": "login_to_setting", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n\tGetHandleVerifier [0x0x7ff699e16f65+78965]\n\tGetHandleVerifier [0x0x7ff699e16fc0+79056]\n\t(No symbol) [0x0x7ff699ba9dda]\n\t(No symbol) [0x0x7ff699c002ea]\n\t(No symbol) [0x0x7ff699c0059c]\n\t(No symbol) [0x0x7ff699c53f37]\n\t(No symbol) [0x0x7ff699c286af]\n\t(No symbol) [0x0x7ff699c50dbe]\n\t(No symbol) [0x0x7ff699c28443]\n\t(No symbol) [0x0x7ff699bf1311]\n\t(No symbol) [0x0x7ff699bf20a3]\n\tGetHandleVerifier [0x0x7ff69a0ce26d+2926461]\n\tGetHandleVerifier [0x0x7ff69a0c8993+2903715]\n\tGetHandleVerifier [0x0x7ff69a0e6aed+3026941]\n\tGetHandleVerifier [0x0x7ff699e316fe+187406]\n\tGetHandleVerifier [0x0x7ff699e396ef+220159]\n\tGetHandleVerifier [0x0x7ff699e1faf4+114692]\n\tGetHandleVerifier [0x0x7ff699e1fca9+115129]\n\tGetHandleVerifier [0x0x7ff699e064d8+10728]\n\tBaseThreadInitThunk [0x0x7ffa099e7374+20]\n\tRtlUserThreadStart [0x0x7ffa0b89cc91+33]\n\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_item\\test_setting.py\", line 32, in login_to_setting\n    page.login(DateDriver().username, DateDriver().password, DateDriver().planning)\n  File \"D:\\PycharmProjects\\APS\\Pages\\login_page.py\", line 30, in login\n    self.enter_username(username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\login_page.py\", line 14, in enter_username\n    self.enter_text(By.XPATH, '//input[@placeholder=\"请输入账户\"]', username)\n  File \"D:\\PycharmProjects\\APS\\Pages\\base_page.py\", line 65, in enter_text\n    element = WebDriverWait(self.driver, wait_time).until(\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 146, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1752739367438, "stop": 1752739381189}], "start": 1752739367438, "stop": 1752739381347}