{"uuid": "271dd371-de4d-462b-b053-63e8f4828507", "children": ["53416d7a-3c58-4d3f-af59-1342e96aaf46"], "befores": [{"name": "login_to_auditlog", "status": "passed", "start": 1758018224908, "stop": 1758018233553}], "afters": [{"name": "login_to_auditlog::0", "status": "broken", "statusDetails": {"message": "KeyboardInterrupt\n", "trace": "  File \"D:\\Program Files\\Python310\\lib\\site-packages\\allure_commons\\_allure.py\", line 231, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 938, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\PycharmProjects\\APS\\Tests\\test_system\\test_auditLog.py\", line 58, in login_to_auditlog\n    safe_quit(driver)\n  File \"D:\\PycharmProjects\\APS\\Utils\\driver_manager.py\", line 50, in safe_quit\n    driver.quit()  # 尝试正常关闭浏览器\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 193, in quit\n    self.service.stop()\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 157, in stop\n    self.send_remote_shutdown_command()\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 142, in send_remote_shutdown_command\n    if not self.is_connectable():\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 131, in is_connectable\n    return utils.is_connectable(self.port)\n  File \"D:\\Program Files\\Python310\\lib\\site-packages\\selenium\\webdriver\\common\\utils.py\", line 101, in is_connectable\n    socket_ = socket.create_connection((host, port), 1)\n  File \"D:\\Program Files\\Python310\\lib\\socket.py\", line 833, in create_connection\n    sock.connect(sa)\n"}, "start": 1758018249559, "stop": 1758018250737}], "start": 1758018224908, "stop": 1758018250737}