[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = //div[@class="ivu-select-head-flex"]/input
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = //li[text()="金属（演示）"]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = //button[contains(@class, "ivu-btn-primary")]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = (//span[text()="系统管理"])[1]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = (//span[text()="单元设置"])[1]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = (//span[text()="配置同步"])[1]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = (//span[text()="PSI设置"])[1]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = (//span[text()="计划运行"])[1]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = (//span[text()="方案管理"])[1]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = (//span[text()="计划方案管理"])[1]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = //table[@class="vxe-table--body"]//tr/td[2]//span[text()="1测试psi1"]
[33mWARNING [0m root:base_page.py:49 ❌ 点击超时：元素 xpath = //table[@class="vxe-table--body"]//tr/td[2]//span[text()="1测试psi1"] 未在 10 秒内变为可点击
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = //table[@class="vxe-table--body"]//tr/td[2]//span[text()="1测试psi2"]
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = //table[@class="vxe-table--body"]//tr/td[2]//span[text()="1测试psi3"]
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F5D3A43A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9eb0ed097e6df15e6c3f1fdcf7277793/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F5D3A7BE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9eb0ed097e6df15e6c3f1fdcf7277793/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F5D3A7DC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9eb0ed097e6df15e6c3f1fdcf7277793/element
[32mINFO    [0m root:base_page.py:43 点击元素：By = xpath, Value = //label[text()="排产方案(订单级)同步1"]
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F5D3A7730>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9eb0ed097e6df15e6c3f1fdcf7277793/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F5D3A7550>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9eb0ed097e6df15e6c3f1fdcf7277793/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F5D3A7490>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9eb0ed097e6df15e6c3f1fdcf7277793/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F5DA63A00>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9eb0ed097e6df15e6c3f1fdcf7277793
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F5DA638E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9eb0ed097e6df15e6c3f1fdcf7277793
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020F5DA639D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9eb0ed097e6df15e6c3f1fdcf7277793
[32mINFO    [0m root:driver_manager.py:55 🛑 已从实例池移除并关闭 driver：2265011875376